task_name: "QASPER"
text_evidence_only: True
deep_or_shallow: 'deep'

count_missing_predictions: True # In cases of missing questions in the predictions, whether to count them into the final result. When true, they count as F1=0